function epsych_printBanner(banneridx)
% ep_printBanner
%
% Print text EPsych banner and a link to the online manual
%
% daniel.stolzberg@gmail.com  8/2016


m{1} = [...
'  _____  ____                     _     '; ...
' | ____||  _ \  ___  _   _   ___ | |__  '; ...
' |  _|  | |_) |/ __|| | | | / __|| ''_ \ '; ...
' | |___ |  __/ \__ \| |_| || (__ | | | |'; ...
' |_____||_|    |___/ \__, | \___||_| |_|'; ...
'                     |___/              '];

m{2} = [...
'________  _______                         __        ';...
'|_   __  ||_   __ \                       [  |      ';...
'  | |_ \_|  | |__) |.--.    _   __  .---.  | |--.   ';...
'  |  _| _   |  ___/( (`\]  [ \ [  ]/ /''`\] | .-. |  ';...
' _| |__/ | _| |_    `''.''.   \ ''/ / | \__.  | | | |  ';...
'|________||_____|  [\__) )[\_:  /  ''.___.''[___]|__] ';...
'                           \__.''                    '];

m{3} = [...
' .____  .___                        _     '; ...
' /      /   \   ____ ,    .    ___  /     '; ...
' |__.   |,_-''  (     |    `  .''   ` |,---.'; ...
' |      |      `--.  |    |  |      |''   `'; ...
' /----/ /     \___.''  `---|.  `._.'' /    |'; ...
'                      \___/               '];

m{4} = [...                                                             
' _|_|_|_|  _|_|_|                                  _|        ';...
' _|        _|    _|    _|_|_|  _|    _|    _|_|_|  _|_|_|    ';...
' _|_|_|    _|_|_|    _|_|      _|    _|  _|        _|    _|  ';...
' _|        _|            _|_|  _|    _|  _|        _|    _|  ';...
' _|_|_|_|  _|        _|_|_|      _|_|_|    _|_|_|  _|    _|  ';...
'                                     _|                      ';...
'                                 _|_|                        '];

m{5} = [...
' _______ _____ _________   __________     _';...
' |______|_____]|______  \_/  |      |_____|';...
' |______|      ______|   |   |_____ |     |'];
                                           
m{6} = [...
' .--. .---.                  .-.   ';...
': .--'': .; :                 : :   ';...
': `;  :  _.''.--. .-..-. .--. : `-. ';...
': :__ : :  `._-.'': :; :''  ..'': .. :';...
'`.__.'':_;  `.__.''`._. ;`.__.'':_;:_;';...
'                  .-. :            ';...
'                  `._.''            '];

m{7} = [...
'  _____  _____    _____ __      __ ____  __    __  ';...
' / ___/ (  __ \  / ____\) \    / (/ ___)(  \  /  ) ';...
'( (__    ) )_) )( (___   \ \  / // /     \ (__) /  ';...
' ) __)  (  ___/  \___ \   \ \/ /( (       ) __ (   ';...
'( (      ) )         ) )   \  / ( (      ( (  ) )  ';...
' \ \___ ( (      ___/ /     )(   \ \___   ) )( (   ';...
'  \____\/__\    /____/     /__\   \____) /_/  \_\  ';...
'                                                   '];

m{8} = [...
' ____     ____                            __         ';...
'/\  _`\  /\  _`\                         /\ \        ';...
'\ \ \L\_\\ \ \L\ \ ____   __  __     ___ \ \ \___    ';...
' \ \  _\L \ \ ,__//'',__\ /\ \/\ \   /''___\\ \  _ `\  ';...
'  \ \ \L\ \\ \ \//\__, `\\ \ \_\ \ /\ \__/ \ \ \ \ \ ';...
'   \ \____/ \ \_\\/\____/ \/`____ \\ \____\ \ \_\ \_\';...
'    \/___/   \/_/ \/___/   `/___/> \\/____/  \/_/\/_/';...
'                              /\___/                 ';...
'                              \/__/                  '];

if ~nargin || isempty(banneridx), banneridx = floor(now); end
banneridx = mod(banneridx,length(m))+1;

cm = cellstr(m{banneridx});
cm{end} = sprintf('%s  <a href="matlab: edit(''%s'')">(C) 2016  Daniel Stolzberg, PhD</a>',cm{end},fullfile(epsych_path,'LICENSE'));
lnk = 'http://dstolz.github.io/epsych/';
cm{end+1} = sprintf('online manual: <a href="matlab: web(''%s'',''-browser'')">%s</a>',lnk,lnk);
cm{end+1} = '-> <a href="matlab: ep_ExperimentDesign">ep_ExperimentDesign</a>  ... Define parameters for experiments';
cm{end+1} = '-> <a href="matlab: ep_BitmaskGen">ep_BitmaskGen</a>        ... Bitmask table generator for behavioral experiments';
cm{end+1} = '-> <a href="matlab: ep_CalibrationUtil">ep_CalibrationUtil</a>   ... Sound calibration utility';
cm{end+1} = '-> <a href="matlab: ep_EPhys">ep_EPhys</a>             ... Electrophysiology experiments with OpenEx';
cm{end+1} = '-> <a href="matlab: ep_RunExpt">ep_RunExpt</a>           ... Behavioral/Electrophysiology with or without OpenEx';

fprintf('\n')
for i = 1:length(cm), fprintf('%s\n',cm{i}); end







